<?php
return [
    [
        'campaignname' => 'Transsion_Native_Campaign_Test_Nov_30_2024',
        'advertiser' => 'TestGP',
        'code' => '1179674AE0080CB1F',
        'appid' => '20241130035104',
        'tld' => 'https://gamestar.shabox.mobi/',
        'portalname' => 'com.imo.android.imoim,com.lemon.lvoverseas&hl=en',
        'creative_type' => '201',
        'creative_id' => 168962,
        'day_capping' => 0,
        'dimension' => '600x600',
        'attribute' => 'rich-media',
        'url' => 'https://gamestar.shabox.mobi/',
        'billing_id' => '900009',
        'price' => 0.1,
        'bidtype' => 'CPM',
        'image_url' => 'https://d2v3eqx6ppywls.c...0baed68c8a54146d3de4.jpg',
        'htmltag' => '',
        'from_hour' => '0',
        'to_hour' => '23',
        'hs_os' => 'ANDROID',
        'operator' => 'Banglalink,GrameenPhone,Robi,Teletalk,Airtel,Wi-Fi',
        'device_make' => 'No Filter',
        'country' => 'BGD',
        'city' => '',
        'lat' => '',
        'lng' => '',
        'app_name' => null,
        'user_list_id' => '0',
        'adplay_logo' => 1,
        'vast_video_duration' => null,
        'logo_placement' => 1,
        'hs_model' => null,
        'is_rewarded_inventory' => 0,
        'pixel_tag' => null,
        'dmp_campaign_audience0' => null,
        'platform' => null,
        'open_publisher' => 0,
        'audience_targeting' => 0,
        'native_title' => 'GameStar',
        'native_type' => 'Native Display',
        'native_data_value' => 'Play Tournament Game',
        'native_data_cta' => 'PLAY N WIN',
        'native_data_rating' => '1',
        'native_data_price' => '1',
        'native_img_icon' => null,
        'native_tracking_url' => null
    ],
    // Add more campaigns as needed
];